### 2.10  错误处理机制
[教程地址：错误处理机制](http://javascript.ruanyifeng.com/grammar/error.html)

---
### 目录
```
1. Error对象
2. JavaScript的原生错误类型
3. 自定义错误
4. throw语句
5. try…catch结构
6. finally代码块
7. 参考连接
```

---
### 1. Error对象
- JavaScript解析或执行时，一旦发生错误，引擎就会抛出一个错误对象。JavaScript原生提供一个`Error`构造函数，所有抛出的错误都是这个构造函数的实例

- `Error`构造函数接受一个参数，表示错误提示，可以从实例的`message`属性读到这个参数

-根据语言标准，`Error`对象的实例必须有`message`属性，表示出错时的提示信息，其他属性则没有提及。大多数JavaScript引擎，对`Error`实例还提供`name`和`stack`属性，分别表示错误的名称和错误的堆栈，但它们是非标准的，不是每种实现都有

---
### 2. JavaScript的原生错误类型
- Error对象是最一般的错误类型，在它的基础上，JavaScript还定义了其他6种错误，也就是说，存在Error的6个派生对象
  - **SyntaxError**:`SyntaxError`是解析代码时发生的语法错误
  - **ReferenceError**:`ReferenceError`是引用一个不存在的变量时发生的错误
  - **RangeError**:`RangeError`是当一个值超出有效范围时发生的错误
  - **TypeError**: `TypeError`是变量或参数不是预期类型时发生的错误
  - **URIError**:`URIError`是URI相关函数的参数不正确时抛出的错误
  - **EvalError**:`eval`函数没有被正确执行时，会抛出`EvalError`错误该错误类型已经不再在ES5中出现了，只是为了保证与以前代码兼容，才继续保留
  
---
### 3. 自定义错误
- 除了JavaScript内建的7种错误对象，还可以定义自己的错误对象

```
function UserError(message) {
   this.message = message || "默认信息";
   this.name = "UserError";
}

UserError.prototype = new Error();
UserError.prototype.constructor = UserError;
上面代码自定义一个错误对象UserError，让它继承Error对象。然后，就可以生成这种自定义的错误了
new UserError("这是自定义的错误！");
```

---
### 4. throw语句
- `throw`语句的作用是中断程序执行，抛出一个意外或错误。它接受一个表达式作为参数，可以抛出各种值
- `throw`可以接受各种值作为参数。JavaScript引擎一旦遇到`throw`语句，就会停止执行后面的语句，并将`throw`语句的参数值，返回给用户
- 如果只是简单的错误，返回一条出错信息就可以了，但是如果遇到复杂的情况，就需要在出错以后进一步处理。这时最好的做法是使用`throw`语句手动抛出一个`Error`对象

---
### 5.  try…catch结构
- `catch`代码块捕获错误之后，程序不会中断，会按照正常流程继续执行下去
- 为了捕捉不同类型的错误，`catch`代码块之中可以加入判断语句

---
### 6. finally代码块
- `try...catch`结构允许在最后添加一个`finally`代码块，表示不管是否出现错误，都必需在最后运行的语句
- `return`语句的执行是排在`finally`代码之前，只是等`finally`代码执行完毕后才返回
